### ISSUE TITLE
[BUG -d option on the new kurly version] kurly -d param=value

### ISSUE THREAD

**Issue by ISFELLY** [davidjpeacock/kurly#104]
Hello, 
i have detected this bug on the new version

OS: RHEL 6.5
Installed version KO : kurly-1.2.1-0.x86_64.rpm
Installed version OK : kurly-1.1.0-0.x86_64.rpm

Request 
kurly -v -d param=value http://10.95.85.148:9000
also tried to add header but same issue
kurly -v -d param=value -H 'Content-Type:application/x-www-form-urlencoded' http://10.95.85.148:9000

Wiresharkee screen shoot
![image](https://user-images.githubusercontent.com/23262126/40613265-2a9dc0e8-627e-11e8-8856-68ad248dbac3.png)

Any help please ?
Thanks

**Comment by ISFELLY** [comment]
Hello @aki237,
I tried to send variable as url params over kurly with -d option it doesn't work with the last version as shown on the wireshark traffic capture.

Any ideas please ? 
Regards

**Comment by aki237** [comment]
@ISFELLY Yes.... Thanks for the Bug report. I think that is fixed in the later commits (01ae088). The error description is also written in that commit message. Any other issues will be glad to help. 😊

**Comment by ISFELLY** [comment]
@aki237  thank you for your help and this great tool , last question how can i get the new rpm  ?

**Comment by aki237** [comment]
@ISFELLY You can compile the program which wouldn't take that much time for golang. I'm yet to setup a copr repo for master. but there is one for release though.

**Comment by ISFELLY** [comment]
Cool thank you
