### ISSUE TITLE
[bug] File input with the --data flag doesn't work

### ISSUE THREAD

**Issue by Gavlooth** [davidjpeacock/kurly#105]
how does kurly -H supposed to work. No matter how i used it, it doesn't seem to change/include a header

**Comment by aki237** [comment]
It works for me.
```kurly -v -H "Content-Type: application/json" https://httpbin.org/anything```

**Comment by Gavlooth** [comment]
kurly -v -H "Content-Type: application/json" \
 -H 'X-Token:AGVcnC2CayiCr3P6dEF4Uey' \
 -d @info.json   -X POST http://httpbin.org/post

or any custom header / data . It would be good to add some trivial examples in the documentation

**Comment by aki237** [comment]
I guess we need a space between the `Key:` and the `Value`
Like :
+ `Key: Value` is right
+ `Key:Value` is not accepted

And the `--data` flag including the `@file` as a form parameter. ie., `"@file"=""`.
I'll try to fix it. Thanks for the bug report @Gavlooth.

**Comment by aki237** [comment]
@Gavlooth If you don't mind I'm changing the Issue heading to be more descriptive.

# Current Heading

```kurly -H```

# Changing to

```[bug] File input with the --data flag doesn't work```

**Comment by Gavlooth** [comment]
--data "key=value" changes    "Content-Type" to "application/x-www-form-urlencoded" no matter what

**Comment by davidjpeacock** [comment]
@Gavlooth If you have time and interest, please build kurly from head and let us know if the issue you found is fixed to your tests.  We'd appreciate your help.

Thank you.

**Comment by Gavlooth** [comment]
if go get github.com/davidjpeacock/kurly builds from head then the following doesnt work 
kurly -H 'Token:eyJhbGciOiJIU' -X POST  http://httpbin.org/post  --data @data.json | jq . 
And after a couple of test nothing seems fixed. Can you provide basic examples to have for 
guidelines ? Also please change  'value' in help with 'key:value' or 'key=value', otherwise is extremely confusing.

**Comment by aki237** [comment]
For example :

 + for the `data` flag say you are sending a `application/x-www-form-urlencoded` content, the
     ```
      kurly -X POST --data "key1=val1&key2=val2&key3=val3" http://something.url
     ```
 + for the `-H` or `--header` flag, the following is followed
     ```
      kurly -X POST --header "Content-Type:application/json;AnotherHeader:HeaderValue;" http://something.url
     ```

This is how curl is programmed, so this is how kurly is supposed to work like.

For ease of use, I removed the necessity of a space between the Colon and the header value.
ie., for `--header` or `-H` flag, Both `Header:Value` and `Header: Value` will work unlike before.
You can see the changes here : https://github.com/davidjpeacock/kurly/commit/7cf4403cd928292a946cea8365b5e8fbd99cf480#diff-7ddfb3e035b42cd70649cc33393fe32c

For any other clarifications, feel free to ask. 😄

**Comment by aki237** [comment]
For example :

+ `kurly --data @data.json -X POST http://httpbin.org/post | jq`
    ```
[<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<] 340 B/340 B
{
  "args": {},
  "data": "",
  "files": {},
  "form": {
    "{\n\t\"name\" : \"kurly\"\n}\n": ""
  },
  "headers": {
    "Accept": "*/*",
    "Accept-Encoding": "gzip",
    "Connection": "close",
    "Content-Length": "22",
    "Content-Type": "application/x-www-form-urlencoded",
    "Host": "httpbin.org",
    "User-Agent": "Kurly/1.2.1"
  },
  "json": null,
  "origin": "xx.xx.xx.xx",
  "url": "http://httpbin.org/post"
}
    ```
+ `kurly --data @data.json -H "Content-Type:application/json" -X POST http://httpbin.org/post | jq`
      ```
{
  "args": {},
  "data": "{\n\t\"name\" : \"kurly\"\n}\n",
  "files": {},
  "form": {},
  "headers": {
    "Accept": "*/*",
    "Accept-Encoding": "gzip",
    "Connection": "close",
    "Content-Length": "22",
    "Content-Type": "application/json",
    "Host": "httpbin.org",
    "User-Agent": "Kurly/1.2.1"
  },
  "json": {
    "name": "kurly"
  },
  "origin": "xx.xx.xx.xx",
  "url": "http://httpbin.org/post"
}
      ```
