### ISSUE TITLE
[Flag] --cookie -b

### ISSUE THREAD

**Issue by davidjpeacock** [davidjpeacock/kurly#33]
-b, --cookie <name=data>
              (HTTP)  Pass  the data to the HTTP server as a cookie. It is supposedly the data previously received from the server in a "Set-Cookie:" line.  The data should be in the format
              "NAME1=VALUE1; NAME2=VALUE2".

              If no '=' symbol is used in the line, it is treated as a filename to use to read previously stored cookie lines from, which should be used in this session if they match. Using
              this method also activates the "cookie parser" which will make curl record incoming cookies too, which may be handy if you're using this in combination with the -L, --location
              option. The file format of the file to read cookies from should be plain HTTP headers or the Netscape/Mozilla cookie file format.

              The file specified with -b, --cookie is only used as input. No cookies will be written to the file. To store cookies, use the -c, --cookie-jar option.

              If this option is used several times, the last one will be used.

**Comment by aki237** [comment]
If the support for reading cookie files is to be added, [this article](https://xiix.wordpress.com/2006/03/23/mozillafirefox-cookie-format/) is the format in which curl stores the cookie in the cookie jar file.

**Comment by aki237** [comment]
For reference :
```
DOMAIN           FLAG         PATH       SECUREFLAG    EXPIRY(Timestamp)   NAME      VALUE
mysite.com    TRUE/FALSE       /         TRUE/FALSE      15122127          lang      en_US
```

in Go terms:
DOMAIN : `http.Cookie.Domain`
FLAG      : Not used probably nowadays.
PATH      : `http.Cookie.Path`
SECUREFLAG : `http.Cookie.Secure`
EXPIRY   : `http.Cookie.Expires`
NAME     : `http.Cookie.Name`
VALUE    : `http.Cookie.Value`

also the HttpOnly option is set by adding the prefix `#HttpOnly_` to the domain field in the cookie text file. That corresponds to the `http.Cookie.HttpOnly` boolean value

**Comment by aki237** [comment]
I have create a go package to parse and write cookies in that file format : [nscjar](https://github.com/nscjar)

**Comment by davidjpeacock** [comment]
Thank you @aki237!
