### ISSUE TITLE
Change default output for HEAD requests

### ISSUE THREAD

**Issue by chr4** [davidjpeacock/kurly#42]
First of all: Thanks for rewriting curl in a safe language! Good idea.

First thing I noticed when integrating kurly into my workflow: I'm using `HEAD` requests often, e.g. `curl -I https://example.com`. When choosing `HEAD`, curl defaults to output the reply headers, which makes sense:

```shell
$ curl -I https://example.com
HTTP/1.1 200 OK
Content-Encoding: gzip
Accept-Ranges: bytes
Cache-Control: max-age=604800
Content-Type: text/html
Date: Mon, 01 May 2017 15:07:13 GMT
Etag: "359670651"
Expires: Mon, 08 May 2017 15:07:13 GMT
Last-Modified: Fri, 09 Aug 2013 23:54:35 GMT
Server: ECS (ewr/15BD)
X-Cache: HIT
Content-Length: 606
```

I expected `kurly` to to this in a similar manner, however, `kurly --request HEAD https://example.com` just prints out the (empty) body. The headers can be viewed when using `-v`, of course, but defaulting the output to something like curl would make sense I suppose.

**Comment by davidjpeacock** [comment]
@chr4 Thank you so much for the report. 👍 

I'm adding this to backlog to work on later.

Great feedback. :-)

**Comment by chr4** [comment]
Closing in favor of #43

**Comment by davidjpeacock** [comment]
@chr4, @alsm Swept in and did great work implementing this correctly! :-)  It's been merged to master so go ahead grab it.

**Comment by chr4** [comment]
Great! Thanks :)
