### ISSUE TITLE
[FLAG] -C --continue-at

### ISSUE THREAD

**Issue by hcorion** [davidjpeacock/kurly#46]
```
-C, --continue-at <offset>
              Continue/Resume a previous file transfer at the given offset. The given offset is the exact number of bytes that will be skipped, counting from the beginning of the source file before it is transferred to the destina‐
              tion.  If used with uploads, the FTP server command SIZE will not be used by curl.

              Use "-C -" to tell curl to automatically find out where/how to resume the transfer. It then uses the given output/input files to figure that out.

              If this option is used several times, the last one will be used.

              See also -r, --range.
```

This is a flag used by Arch Linux's makepkg, and it uses `-C -`

**Comment by davidjpeacock** [comment]
Thank you @hcorion.  Adding to backlog.

**Comment by davidjpeacock** [comment]
Content-Range header info - https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html

**Comment by aki237** [comment]
is this done?

**Comment by davidjpeacock** [comment]
No, sorry, I closed it in error.  I moved it back to backlog from PR Review
since the code in review was very stale, I threw the branch away.

This still needs to be implemented.

**Comment by aki237** [comment]
what if the server doesn't accept ranges? Start from first?

**Comment by davidjpeacock** [comment]
That's ambiguous.  According to the RFC:

14.5 Accept-Ranges

      The Accept-Ranges response-header field allows the server to
      indicate its acceptance of range requests for a resource:
          Accept-Ranges     = "Accept-Ranges" ":" acceptable-ranges
          acceptable-ranges = 1#range-unit | "none"
      Origin servers that accept byte-range requests MAY send
          Accept-Ranges: bytes
      but are not required to do so. Clients MAY generate byte-range
      requests without having received this header for the resource
      involved. Range units are defined in section 3.12.
      Servers that do not accept any kind of range request for a
      resource MAY send
          Accept-Ranges: none
      to advise the client not to attempt a range request.

As for what to do in this situation, my gut would be go make it cURL-like.

**Comment by aki237** [comment]
So I made a non resumable server and tested it with cURL : 

    curl: (33) HTTP server doesn't seem to support byte ranges. Cannot resume.

**Comment by davidjpeacock** [comment]
Seems reasonable.  Do you want to implement this feature?

**Comment by aki237** [comment]
sure

**Comment by aki237** [comment]
Another thing : [this line](https://github.com/davidjpeacock/kurly/blob/master/options.go#L222) has to be os.Open with right flags. For continue to work, File should be opened with flags `os.O_CREATE|os.O_RDWR`. `os.Create` according to godoc : 

    func Create(name string) (*File, error)
        Create creates the named file with mode 0666 (before umask), truncating
        it if it already exists. If successful, methods on the returned File can
        be used for I/O; the associated file descriptor has mode O_RDWR. If
        there is an error, it will be of type *PathError.

**Comment by aki237** [comment]
I think I have solved this. Tested it with a debian netinst iso (200M), the sha512 was the same from the site after the full download.

**Comment by davidjpeacock** [comment]
Thank you @aki237! 👍
