### ISSUE TITLE
Error while installing with go get

### ISSUE THREAD

**Issue by shipup** [davidjpeacock/kurly#47]
When I run :
`go get github.com/davidjpeacock/kurly`
in terminal I get this error:
`# github.com/davidjpeacock/kurly
.go/src/github.com/davidjpeacock/kurly/options.go:141: undefined: http.ErrUseLastResponse`

go version go1.6.2 linux/amd64

**Comment by alsm** [comment]
`http.ErrUseLastResponse` was introduced in go 1.7, kurly will require at least this version to run (not sure if there are any other uses of features > 1.7) We'll determine this and put it in the docs.

**Comment by davidjpeacock** [comment]
@shipup Thank you for the report BTW! 👍
