### ISSUE TITLE
No issue, just appreciation

### ISSUE THREAD

**Issue by carlca** [davidjpeacock/kurly#48]
Hi David, as the title suggests there are no issue (that I've found so far!), I just wanted to say thanks and well done on a useful utility. The beauty of it for me as a novice Golang developer is that it will be a valuable learning resource, especially on the usage of command line flags.
Thanks again,
Carl

**Comment by davidjpeacock** [comment]
Thank you for the kind words @carlca!

@alsm and I are very pleased both with what we've accomplished, and the reception kurly is currently getting.  Thank *you*!

For a simple application the default Golang `flag` package is likely all you need, but indeed for a more complex tool, something like `github.com/urfave/cli` is certainly the way to go. 👍 

Thanks again for the feedback; feel free to let us know of any issues you encounter.

Cheers,
David & Al
