### ISSUE TITLE
FTP support?

### ISSUE THREAD

**Issue by bengadbois** [davidjpeacock/kurly#54]
Curl supports a number of FTP features. Will kurly do this, or is kurly limiting the scope to HTTP?

Not a feature request, more a question of clarity

**Comment by davidjpeacock** [comment]
Hey @bengadbois,

This is a good question, and one I'm going back and forth on.  My gut is that FTP is dead or dying, and as such I don't see the need to add support for it to kurly.  I don't know anyone who still uses it, and even the Debian project recently announced that they're turning it off on their distribution servers.

I think, unless there is high demand for it, we'll likely not go for it.

https://www.debian.org/News/2017/20170425

Cheers,
David
