### ISSUE TITLE
Cut 1.1 release

### ISSUE THREAD

**Issue by davidjpeacock** [davidjpeacock/kurly#66]
I think there's enough good stuff since the initial launch to cut a new release.

Logging this issue to track.

@alsm @aki237 

Any thoughts?

**Comment by aki237** [comment]
@davidjpeacock Yeah... 1.1 🎊 🎉

**Comment by aki237** [comment]
We can close this now!

**Comment by davidjpeacock** [comment]
Right you are @aki237!

Thanks again for all your contributions. 👍 :-)
