### ISSUE TITLE
[headers] : update the User-Agent

### ISSUE THREAD

**Issue by aki237** [davidjpeacock/kurly#71]
This is more of a question than a issue. Should we update the user agent for every new release?
[User agent option](https://github.com/davidjpeacock/kurly/blob/master/options.go#L129)

**Comment by davidjpeacock** [comment]
Answer:  We need to adjust the User-Agent to be inline with the kurly version.

This would be good low hanging fruit for a new contributor!

**Comment by aki237** [comment]
I think we can close this issue now @davidjpeacock
