### ISSUE TITLE
[output] printing binary content

### ISSUE THREAD

**Issue by aki237** [davidjpeacock/kurly#83]
cURL warns users if the incoming content contains binary output if it has to print it in the stdout (no output file specified)
Example :
```
Warning: Binary output can mess up your terminal. Use "--output -" to tell 
Warning: curl to output it to your terminal anyway, or consider "--output 
Warning: <FILE>" to save to a file.
* Failed writing body (0 != 4078)
* stopped the pause stream!
* Closing connection 0
```
I think kurly should also give out a warning in that case.
What do you think @davidjpeacock ?

**Comment by davidjpeacock** [comment]
Great idea @aki237 :+1:
