### ISSUE TITLE
Release and package build automation

### ISSUE THREAD

**Issue by davidjpeacock** [davidjpeacock/kurly#91]
This process is laborious and prone to error.

Must automate.

**Comment by davidjpeacock** [comment]
* Version numbering update in spec, man page, changelog, main.go
* Tagging after the fact
* Release builds including RPM

**Comment by aki237** [comment]
PIN : https://paste.ubuntu.com/p/f99G7C3qr2/

**Comment by aki237** [comment]
@davidjpeacock Hey, I've written a hacky script to check all the todo things for a new tagged release.

Pending changes :
![pre-tag-checker-script](https://user-images.githubusercontent.com/8568726/37362761-186adad4-271c-11e8-8ed1-df87cf4b643c.png)
It also helps by spitting out the current date in needed formats for different places.

All done :
![image](https://user-images.githubusercontent.com/8568726/37362816-4856f962-271c-11e8-8ecc-1a8debdc01ae.png)

Can this be added for now?

**Comment by davidjpeacock** [comment]
@aki237 Let's put all such things in this new repo:

https://github.com/davidjpeacock/metakurly

**Comment by aki237** [comment]
like? `meta/*` + the check script?

**Comment by client9** [comment]
hi team, love the project.

My apologies if you looked into this and rejected it, but checkout 

* https://goreleaser.com 
* https://github.com/goreleaser/goreleaser

it not only will cross-compile kurly in all the OS/Arch format you want, in all the package formats you want,  pushing them to GitHub  releases and then even create a shell script to simplify install and download.  All you gotta do is create .yaml and the release tags.  Everything is done.

I'm happy to help walk you through the process and/or create a PR for you.

n

disclaimer: I wrote the goloader/install scripts, but I'm a big fan of kurly!

**Comment by aki237** [comment]
@client9 Thanks for taking an interest in this project. Will definitely take a look at goreleaser. Can you state what else it can do apart from pushing to github and building different package formats? Like in this specific case, say we can build RPM using goreleaser, (so no spec file needed), We'll need it to check the version number in the go files, and the other documents that had to be packaged like the man page for a new release. I would love if you can brief about it a little bit.

Thanks.
